# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZJRUAN
email: rzhj@vip.qq.com
description: > # this means to ignore newlines until "baseurl:"
  写博客一方面是为了分享，更多的是记录一些知识，方便日后回忆，同时也加深自己对该知识的理解。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  zjruan

baseDomain: http://www.zjruan.com
# Build settings
markdown: redcarpet
redcarpet:
  extensions: [ "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
